### ISSUE TITLE
Pointers to enemies

### ISSUE THREAD

**Issue by Waog** [Waog/TeddyDefender#1]
- [x] proper graphics
  - [x] round icon for each monster type
- [x] integrate graphics

**Comment by stefgame** [comment]
In Dropbox. Folder:Pointers.

Sie sind erstmal ganz einfach gehalten... Sollten aber ihren Zweck damit erfüllen.

**Comment by Waog** [comment]
Kannste mir da noch Icons von den monstern reinmachen? Also vllt erstmal eifach das grüne und rote zentriert in der mitte?

**Comment by Waog** [comment]
erstmal ohne icons in der mitte einbauen

**Comment by stefgame** [comment]
Ich hab die Pointer mal geupdated... Siehe Dropbox. Sind zwei versionen je Monster.. Kannst ja mal schauen welche du besser findest.
