### ISSUE TITLE
teddy movement

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#10]
- [x] doppel klick - attacke: zuhauen und springen
  - [x] animation
- [x] einfach klick - laufen zum ziel
  - [x] graphic goal indicator
- [x] teddy walks quicker oder beschleunigt nach ein paar sekunden
  - [ ] rennanimation
- [x] swipen - verlegt auf später #27

**Comment by Waog** [comment]
Wir brauchen jetzt eine grafik für einen Ziel-Indicator. Habe erstmal irgendeine eingefügt:
![teddy-moving](https://cloud.githubusercontent.com/assets/5098472/13460341/4641cbec-e07a-11e5-95aa-bb251eb50366.gif)

**Comment by Waog** [comment]
Zwischenstand Teddy Attack:
![teddy-attacking](https://cloud.githubusercontent.com/assets/5098472/13461463/d6f01a8e-e081-11e5-9464-65b56d2f7e9f.gif)

**Comment by Waog** [comment]
okay, neue grafiken und animationen müssen jetzt her

**Comment by stefgame** [comment]
![image](https://cloud.githubusercontent.com/assets/17235993/13521980/886f5558-e227-11e5-8bc8-b62fa0f69d79.png)

**Comment by Waog** [comment]
- die ausgangspositionen finde ich beide komisch... ich glaube wenn man normal mit nem schwert in der hand rennt, dann ists fast grade nach vorne ausgerichtet. und die Arme können ruhig enger an den körper, weil sie nicht so weit abstehen.
- finds irgendwie komisch, dass in position 4 das schwert plötzlich nach innen statt außen zeigt. man muss beim schlagen ganz komisch sein handgelenk verdrehen um so zu schlagen.
- cool finde ich dass teddy aus dem körper schlägt, statt nur aus dem arm und auch den linken arm zum schwung holen nutzt.
- die verdrehte endposition bietet sich auch für Angriffs-Kombos an #33

**Comment by stefgame** [comment]
Animiert. Muss jetzt von dir wieder integriert werden.

**Comment by stefgame** [comment]
Animation done..for now.
