### ISSUE TITLE
Kind wacht auf

### ISSUE THREAD

**Issue by Waog** [Waog/TeddyDefender#12]
- [x] Kind hat Schlafmeter
  - [x] Design nötig
- [x] Wenn Schlafmeter auf 0 -> Game over
- [x] Schlafmeter regeneriert

**Comment by Waog** [comment]
Habe grad n tutorial gesehen... ein Balkenförmiges Schlatmeter wäre erstmal leicht umzusetzen... vllt sogar ohne grafiken von dir und nur mit guter farbwahl....

**Comment by stefgame** [comment]
Hab mal ein Schlafmeter in die Dropbox gelegt. Im UI folder.
