### ISSUE TITLE
Game starter & mood drawing

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#16]
In regards to the Concept drawing Thing..

Ich dachte ich mach mal nen Update rein von dem was ich so gerade gemacht habe.
Gleichzeigtig brauchen wir ja auch noch ein Game loading Screen und vllt kann man das beides Vereinen.
Also hier mal nen Screenshot vom momentanen Stand der Lage. Sag mal was du davon hältst.

![image](https://cloud.githubusercontent.com/assets/17235993/13203404/5eab3a2c-d8f2-11e5-91b2-3b0c6f47e666.png)

**Comment by Waog** [comment]
Strichführung und Schattierung finde ich cool, die Farbwahl noch zu beißend. Teddy könnte ruhig noch mehr Kindchenschema haben.

Hast du schon irgendwelche collagen von anderen spielen/kunstwerken zur insperation? die würde ich auch gerne mal sehen, um vllt meinungen abzugeben bevor du zu viel Zeit in eigenes steckst.

**Comment by Waog** [comment]
Hab das hier grade entdeckt und etwa sowas hatte ich bei den alpträumen im sinn:

![image](https://cloud.githubusercontent.com/assets/5098472/13248057/c2f6665c-da1c-11e5-8783-39f67605631e.png)

**Comment by stefgame** [comment]
Im folgenden mal drei Colours Schemes... Du wirst sehen das das Monster inzwischen erstmal einfach nur ne Wolke mit Augen ist.
kannst mir ja mal nen Feedback geben. Nen kleinen favouriten hab ich ja.

![image](https://cloud.githubusercontent.com/assets/17235993/13358727/be0e9390-dceb-11e5-9995-af0c799cd39d.png)
![image](https://cloud.githubusercontent.com/assets/17235993/13358730/be7c3166-dceb-11e5-861d-e207dc8db582.png)
![image](https://cloud.githubusercontent.com/assets/17235993/13358731/be80f61a-dceb-11e5-81a0-b281ac111348.png)

**Comment by Waog** [comment]
Also im Moment tendiere ich zum zweiten. Aber jedes hat stärken und schwächen, ie man vielleicht noch verstärken und verringern kann.
1. ist cool nachtig/alptraumig, aber zu wenig kontraste. Vielleicht zu eintönig, ums längerer Zeit zu spielen.
2. ist schon etwas blut-themed oder auch drittes reich. Passt gut, wenn wir unser setting in diese Richtung lenken wollen... Vampire, Blutsauger, Nazis, Zombies. Oder so the-ring/slender-man mäßig, wenns weiße monster sind.
3. ist am vielfältigsten und süßesten, dafür wenig alptraumartig, mehr so gemütliche kuschelige nacht. Das Monster sieht aus wie ein Kackhaufen ^^

Insgesamt würde ich sagen, dass wir mit den Kontrasten anders arbeiten müssen. Hintergründe (Teppich, Schränke) müssen deutliche Kontraste zu spielrelevanten Elementen (Monster, Teddy) haben und in sich (Schrank<->Teppich) eher weniger Kontraste haben. In allen drei Schemas wäre es also klarer wenn die Farben von Schränken und Monster vertauscht wären.

**Comment by stefgame** [comment]
![image](https://cloud.githubusercontent.com/assets/17235993/13373749/01c732e4-ddab-11e5-99d8-2911ade1c99c.png)

**Comment by Waog** [comment]
hatte grad noch ne idee, aber weiß nicht wie leicht die umsetzung wäre. Kannst erstmal sagen was du davon hällst:

wir könnten mehr mit licht arbeiten (fackeln, taschenlampen etc.) und immer allem was beleuchtet ist ein bunteres farbspektrum geben. und dieses farbschema nur an unbeleuchteten stellen (die noch den großteil ausmachen sollten) nutzen. Was meinste?

**Comment by Waog** [comment]
@stefgame keine meinung zu meiner frage?
