### ISSUE TITLE
2 Bugs: jumping camera & monsters in wall.

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#19]
Ich hab mal zwei kleine Videos in die Dropbox gelegt.ich konnte sie hier nicht hochladen.

Das eine zeigt das Teddy und die Monster immer noch In der Wand stecken und beim zweiten sieht man wie der Screen extrem flackert beim zoomen. Das passiert vor allem dann wenn viele Monster da sind. Eine weitere Frage: ich find das ausgezoomt sooooooo viel besser. Und auch nicht unbedingt zu klein. Ich finde auch immer noch das es am besten wäre wenn der zoom durch eine zwei Finger Bewegung geregelt werden würde.

**Comment by Waog** [comment]
Finde nur ein Video in der box. Das mit _in der Wand stecken_ fehlt und habs auch noch nicht bei mir gehabt!? Hier in github kann man die auch nicht hochladen.

Die Zoomstufe können wir festlegen wenn das spiel fertiger ist.
Zu weit rausgezoomt ergibt sich wieder das ursprüngliche Problem mit dem Seitenverhältnis. Solange wir dafür keine sinnvolle Lösung haben, müssen wir also etwas reingezoomt bleiben.

Ob zoom durch zwei finger oder einen slider geregelt wird, ist egal, weil der Spieler sowieso nichts von beidem tun soll. Der slider ist nur für uns, um leichter verschiedene Stufen auszuprobieren.

**Comment by stefgame** [comment]
Hmhm weird.. Keine Ahnung warum es nicht da war, aber habe es jetzt nochmal hin zu gefügt.

**Comment by Waog** [comment]
Monsters in wall ist intressant, bis wir die richtigen monster eingebaut haben...
