### ISSUE TITLE
Schatten

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#6]
- [ ] Schatten grafik
  - [ ] Teddy
  - [ ] Monster
- [ ] Oli in spiel eingebaut

**Comment by Waog** [comment]
![image](https://cloud.githubusercontent.com/assets/5098472/13075473/b2e04538-d4ab-11e5-8e19-1d4dcbbf6e3f.png)

**Comment by stefgame** [comment]
Werd ich jetzt immer mit den neuen Grafiken direkt dazu machen.
