### ISSUE TITLE
Game Over Screens

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#7]
- [x] Game over screens ins spiel einbauen

**Comment by stefgame** [comment]
Neuer Teddy stirbt background in Dropbox..... Sag mir mal was du von dem hältst.

![image](https://cloud.githubusercontent.com/assets/5098472/13285939/45c20708-dafe-11e5-8fb2-b6bf6d4b34c5.png)

**Comment by Waog** [comment]
Hab hier die gleiche meinung wie in #16. Coole Formen, zu beißende Farben.

**Comment by stefgame** [comment]
Mal ein bisschen an den Farben gedreht.... Die dunklen haben mich erstmal voll deprimiert ..Na ist Game over..ist vllt so...aber das helle find ich irgendwie auch ganz gut......was denkst du??

![image](https://cloud.githubusercontent.com/assets/17235993/13290190/bd1ce8a0-db4d-11e5-9482-eeb6cf01923f.png)
![image](https://cloud.githubusercontent.com/assets/17235993/13290191/bd7156f6-db4d-11e5-83b0-6f345e0f657d.png)
![image](https://cloud.githubusercontent.com/assets/17235993/13290192/bd734754-db4d-11e5-8b2a-ca2f0dd17467.png)

**Comment by Waog** [comment]
- Das dunkle löst irgendwie das Farbproblem nicht wirklich auf. Ist vllt sogar schlimmer geworden... Der Sprung von Braun zu Blau ist irgendwie unangenehm
- Jo, ich steh auf Pastellfarben. Das gefällt mir viel besser.
- Nur blau ist irgendwie zu trist... glaube 2 Farben sollten schon da sein. Nur halt matchende...

**Comment by stefgame** [comment]
Ok find I cool... Hatte die Farben von dem hier geklaut und fand die Stimmung auf dem Bild so schön

Aber weiß wie immer nicht genau ob es auch zu unserem spiel passt..,ma schauen

![image](https://cloud.githubusercontent.com/assets/17235993/13291498/ec60d130-db52-11e5-99f7-25b030760118.png)

**Comment by Waog** [comment]
Mir hat der Artikel hier etwas geholfen beim Farben finden... bin aber immernoch ein Krebs darin: http://www.2dgameartguru.com/2013/06/choosing-your-highlight-and-shader.html

**Comment by Waog** [comment]
Game Over für aufwachendes Kind ist eingebaut

![image](https://cloud.githubusercontent.com/assets/5098472/13341145/3b3b84ba-dc36-11e5-9948-6dc6afd2aaf2.png)

**Comment by stefgame** [comment]
3A7477 für Hintergrundfarbe erstmal
Neues file liegt in der dropbox

**Comment by Waog** [comment]
Game Over durch Teddy-Tod bleibt erstmal weg, bis Teddy auch wirklich sterben kann.
