### ISSUE TITLE
New Monsters Graphics

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#8]
- [x] Monstertyp 1: kleines moschmonster
- [x] Monstertyp 2: grosses monster, wunden oder ähnliche indication das monster schwächer wird

**Comment by stefgame** [comment]
Neues moschmonster?

![image](https://cloud.githubusercontent.com/assets/17235993/13196006/4b67fae0-d7fd-11e5-8c78-59973456062c.png)

**Comment by Waog** [comment]
Warum heißt es moschmonster? Kann das moschen oder nur umgemoscht werden?

Also ich finds ziehmlich cool, wenn auch wenig Alptraumartig (durch die Farbwahl). Erinnert mich mehr an _Teddy den Schädlingsbekämpfer_. Können wir meinetwegen so nehmen, aber bin mir noch unklar wie dann der Overall-Artstyle (#18) aussehen soll.

**Comment by stefgame** [comment]
Ich finds total scheisse inzwischen..wie alle meine Monster.

**Comment by stefgame** [comment]
Ich hab eindeutig ein Monster problem.

**Comment by Waog** [comment]
Dann identifiziere WAS du genau daran scheiße findest und ändere genau das.

**Comment by stefgame** [comment]
Hab jetzt einen Single Wolken strich in die Dropbox gelegt, sowie die roten Augen. 250x250px.

Sag mal ob das alles ist was du für die Animation brauchst.

**Comment by Waog** [comment]
Könnte reichen... probiere ich bei Gelegenheit aus.

**Comment by Waog** [comment]
![ghosts](https://cloud.githubusercontent.com/assets/5098472/13467251/aa15a314-e09d-11e5-8ded-65b6f03e77ee.gif)

**Comment by Waog** [comment]
großes monster fehlt noch

**Comment by stefgame** [comment]
Finds ganz gut. Was denkst?also als großes moschmonster.

![image](https://cloud.githubusercontent.com/assets/17235993/13703027/b98b929a-e7cd-11e5-97db-628fa566dc18.png)

**Comment by Waog** [comment]
Ich würde glaub ich großes und kleines monster tauschen. Es ist irgendwie glaubwürdiger, dass eine weiße Wolke einfach wächst, als dass ein Wurm wächst.

Könnte gut aussehen der Wurm... kannst du den mal über das Zimmer legen, dass ichs im gesamten (vor nem Hintergrund) sehe?

Dadurch dass das monster auch so hell ist, haben die jetzt alle sowas ghost-mäßiges. Ist irgendwie cool.

**Comment by stefgame** [comment]
![image](https://cloud.githubusercontent.com/assets/17235993/13727124/ad35b080-e920-11e5-8da5-d8af00f1a030.png)

**Comment by stefgame** [comment]
Hab Teddy auch so mehr oder weniger nochmal gezeichnet..das Monster auch...jetzt muss ich sie ja nur noch animieren.... O.o

**Comment by Waog** [comment]
Ja, könnte cool aussehen, wenn das monster sone lichtaura bekommt. Was meinste?

**Comment by stefgame** [comment]
Done.

**Comment by Waog** [comment]
Ekelwurm animationen sind irgendwie buggy... wir müssen die zusammen nochmal aufräumen. Aber habs erstmal eingebaut.
