### ISSUE TITLE
Zimmer graphics

### ISSUE THREAD

**Issue by stefgame** [Waog/TeddyDefender#9]
Neue Zimmer Grafiken ins Spiel einbauen.

**Comment by stefgame** [comment]
Was hältst du von diesem style?

![image](https://cloud.githubusercontent.com/assets/17235993/13197020/aea8ea06-d81b-11e5-864d-5197888a37ab.png)

**Comment by Waog** [comment]
Mach mal bei solchen Issues zukünftig _[needs discussion](https://github.com/Waog/TeddyDefender/labels/needs%20discussion)_-label dran, oder weise mir den issue zu, wenn du ne antwort erwartest. Geht sonst vllt unter zwischen den anderen issues.

Kann mir den Style insgesamt noch schwierig vorstellen... also wie dazu monster und möbel aussehen. Beißt das grüne Moschmonster (#8) nicht auf dem blauen boden? Für sich genommen find ich:
- Das Bett+Kind gut vom Style her
- Den Boden etwas zu langweilig, könnte aber gut sein, wenn mehr Elemente im Zimmer sind.
- Die Wände zu abweichend vom restlichen style. Vllt genauso "schampig" gezogene wände wie die Linien auf dem Boden? Also ruhig etwas ungerade?

**Comment by stefgame** [comment]
Neue Hintergrund pngs liegen in der Dropbox im background folder. Du wirst sehen das es das ganze Zimmer als komplettes Image gibt oder die Möbel und Hintergrund einzeln. Wir müssen nochmal besprechen in was für Einzelteile wir den Hintergrund zerstückeln wollen. Theoretisch kann ich dir jedes Fenster und Schatten ja als einzelne Datei geben falls das irgendwelche Vorteile bringt.
